src/Latte/Compiler.php, src/Latte/Engine.php
Also the Compiler also has `CONTENT_URL`. Should we add it? Should the `Compiler` be updated to load the constant values from the `Engine`?
=> Engine: inlined constant values to avoid loading Compiler in runtime

src/Latte/Macros/BlockMacros.php, src/Latte/Macros/BlockMacrosRuntime.php, src/latte.php, tests/Latte/expected/macros.dynamicblock.phtml, tests/Latte/expected/macros.includeblock.phtml, tests/Latte/expected/macros.inheritance.child1.child.phtml, tests/Latte/expected/macros.inheritance.child1.parent.phtml
Splitting prevents loading `MacroSet.php` and `IMacro.php` files in runtime. Were the runtime helpers considered internal or should I keep them in `BlockMacros` for compatibility?
=> BlockMacros: runtime helpers moved to BlockMacrosRuntime

src/Latte/Runtime/Filters.php, tests/Latte/Filters.nl2br().phpt
Former change could cause potential hidden XSS errors as the whole string was being unescaped.
This reverts commit 86b55f5d8e7b0ed182404df987107e905a7f974f.
=> Revert Filters: Update nl2br to return Latte\Runtime\Html object

src/Latte/Engine.php, tests/Latte/Engine.parseError.phpt
it is ok in the master, but in v2.3 branch, `$e` is overwritten and wrong line number is passed to the CompileException.
=> Engine: fixed CompileException sourceLine on PHP7

src/Latte/Loaders/FileLoader.php
I was googling in my brain quite long to understand the reason, why is touching done.
=> FileLoader: error message explaining touching, when touch() fails

src/Latte/MacroTokens.php, src/Latte/PhpWriter.php, tests/Latte/PhpWriter.formatArgs().phpt
Now it is treated as a short ternary
=> Respect null coalesce operator

src/Latte/Engine.php, tests/Latte/Engine.providers.phpt
This method allows to get all providers passed to the Latte\Engine using method Latte\Engine::addProvider. It useful for example when you have custom Template object and you need to work there with providers.
see: https://forum.nette.org/cs/26250-pojdte-otestovat-nette-2-4-rc?p=3#p175305
=> Latte\Engine: add getProviders method

src/Latte/Runtime/Filters.php, tests/Latte/Filters.substring().phpt, tests/Latte/Filters.truncate().phpt
`Filters::truncate` & `Filters::substring` should not use `Filters::length` because posibility of object which is `Countable` or `Traversable` and has magic method `__toString`.
For example, in Latte `{$article}` works well, but `{$article|truncate:20}` don't and that is imho inconsistent behaviour. What do you think?
=> Filters: remove use of length from truncate & substring methods

src/Latte/Runtime/ISnippetBridge.php, src/Latte/Runtime/SnippetDriver.php, tests/Latte/mocks/SnippetBridge.php
https://forum.nette.org/cs/26805-sekundarni-sablona-komponenty-ignoruje-makro-extends-pri-ajaxu
But it is a bc break. Is that ok with you?
=> Snippets: disable snippet mode when rendering snippets

src/Latte/Macros/BlockMacros.php, tests/Latte/BlockMacros.defineblock.phpt, tests/Latte/expected/BlockMacros.defineblock.html, tests/Latte/expected/BlockMacros.defineblock.phtml
...when named parameters are used
currently, even global variables like `$basePath` are not available...
=> BlockMacros - define: fixed variables extracting

src/Latte/Loaders/FileLoader.php, tests/Latte/Loaders.FileLoader.phpt
Fixes #138 by just remembering these `..` parts and the add them to the rest when normalizing the path
Thanks for considering this fix!
=> Make normalizePath() not forget leading ../

src/Latte/Macros/CoreMacros.php
When the first and only argument to n:attr macro is an array, expand it.
- bug fix? no
- new feature? yes
- BC break? yes, in a rare (and not really sensible) case
I opened another PR **solving the same thing** by adding a new macro here: #157
**Motivation**:
Suppose there is an array `$attributes` containing attributes for `<meta>` tag.
```php
array (
'content' => 'width=device-width, initial-scale=1',
'name' => 'viewport',
'http-equiv' => NULL,
'scheme' => NULL,
)
```		
The developer wants to achieve this HTML output:
```html
<meta content="width=device-width, initial-scale=1" name="viewport">
```
However, using `<meta n:attr="$meta">` the actual output is:
```html
<meta 0="content:width=device-width, initial-scale=1 name:viewport">
```
The developer is currently forced to use …
=> feature: macro n:attr expands arrays

src/Latte/Compiler/MacroTokens.php, tests/Latte/expected/macros.n-macros.html, tests/Latte/expected/macros.n-macros.phtml, tests/Latte/templates/macros.n-macros.latte
- bug fix? yes
- new feature? no
- BC break? no
[BEM](http://getbem.com/naming/) use `--`  for modifiers. Now it's possible to use classes like `block--hidden` in `n:class` without quotes.
=> n:class supports BEM

src/Latte/Loaders/FileLoader.php
Method was called from `getContent` with the full file path (see lines 36 and 43) and inside the method `isExpired` baseDir was added another time (see line 57), so as the result we have: "baseDir/baseDir/fileName.ext"
https://github.com/nette/latte/blob/e6ab6ccc5c372036b99bf8b03c2b6ff9f1cec621/src/Latte/Loaders/FileLoader.php#L34-L43
https://github.com/nette/latte/blob/e6ab6ccc5c372036b99bf8b03c2b6ff9f1cec621/src/Latte/Loaders/FileLoader.php#L55-L57
Fix for *2.4* branch, but it should be also fixed on master.
- bug fix? yes/~no~   
- new feature? ~yes~/no
- BC break? ~yes~/no
- doc PR: ~nette/docs#???~
=> [2.4] Hotfix - `isExpired` correct file path

src/Latte/Runtime/CachingIterator.php, tests/Latte/CachingIterator.basic.phpt
When an iterator has been used in a template just as `{$iterator}` and not
as `{$iterator->counter}` (as documented), it has thrown a kind of confusing
error:
Fatal error: Method Latte\Runtime\CachingIterator::__toString() must not
throw an exception, caught BadMethodCallException: Latte\Runtime\CachingIterator
does not fetch string value (see CachingIterator::__construct) in *PATH* on line 0
This patch allows conversion to a string by returning the current counter.
- bug fix? yes
- BC break? no
=> added CachingIterator::__toString()

src/Latte/Compiler/Compiler.php, tests/Latte/Compiler.emptyMacros.phpt
- bug fix: #176 
- BC break? no
- doc PR: no needed
This PR has 2 changes:
- upgrade nette/tester to v2.0
- allow to use own Compiler with no defined macros
=> Allow to have no macros in Compiler

src/Latte/Runtime/Filters.php
A long time ago it was possible to use the replace filter like this:
{$var|replace:[' ','+']:['','00']}
Today it ends up like this:
Argument 3 passed to Latte\Runtime\Filters::replace() must be of the type string, array given
Is it possible to avoid this BC break?
=>  Filters: remove string type hints from replace filter

src/Latte/Runtime/FilterExecutor.php
- bug fix
- BC break? no (function is available since 7.1.0)
Function ReflectionType::__toString() is deprecated, use getName() instead.
=> Fix compatibility with PHP 7.4

src/Latte/Runtime/Filters.php, tests/Latte/expected/macros.general.html.html, tests/Latte/expected/macros.general.html.phtml, tests/Latte/expected/macros.general.xhtml.html, tests/Latte/expected/macros.general.xhtml.phtml, tests/Latte/macros.general.html.phpt, tests/Latte/macros.general.xhtml.phpt, tests/Latte/templates/general.latte
- bug fix
- BC break? no
- doc PR: not needed
435139bf5b75f811ffef3e79cc84d4170a7946d0 broke compatibility with nette/utils - this package still uses `I` prefix on interfaces, namely there is `HtmlString` interface, it's still called `IHtmlString`.
=> Filters: fix escaping of IHtmlString from nette/utils

src/Latte/Compiler/Compiler.php
<script type="module">//…</script> would by also be Javascript context ( Compiler::CONTEXT_HTML_JS )
attribute type="module" on script elementy is necessary for using dynamic javascript import ( https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import )
=> <script type="module"> is also javascript context

src/Latte/Macros/BlockMacros.php, src/Latte/Macros/CoreMacros.php, tests/Latte/BlockMacros.include.with-blocks.phpt, tests/Latte/BlockMacros.inheritance.child1.phpt, tests/Latte/contentType.compatibility.phpt, tests/Latte/expected/BlockMacros.include.inc1.phtml, tests/Latte/expected/BlockMacros.include.phtml, tests/Latte/expected/BlockMacros.include.with-blocks.html, tests/Latte/expected/BlockMacros.include.with-blocks.inc.phtml, tests/Latte/expected/BlockMacros.include.with-blocks.phtml, tests/Latte/expected/BlockMacros.inheritance.child1.phtml
- bug fix? ~
- new feature? yes
- BC break? no
There are use cases where `{includeblock}` is useful and cannot be substituted by `{import}`. But the name `{includeblock}` is misleading. This is attempt to solve it by more understandable `{include with blocks 'file.latte'}`
Cons: this introduces syntax which is not common in Latte.
https://forum.nette.org/cs/26699-latte-vypis-bloku-do-include
=> added {include with blocks} as a successor to {includeblock}

src/Latte/Engine.php
- typo fix
- no
- n/a
Fixed a typo in missing intl extension exception message, made the message a bit more verbal
=> Fix typo in intl-related locale exception message
